captcha:
    height: 80
    width: 240
    length: 6
    max_skew: 0.7
    dot_count: 80
email:
    host: smtp.qq.com
    port: 465
    from: 3263296956@qq.com
    nickname: Askanuo
    secret: mbmqohmoplfwciie
    is_ssl: true
es:
    url: http://127.0.0.1:9200
    username: ""
    password: ""
    is_console_print: true
gaode:
    enable: true
    key: 8d804c46773430843e51f3163370fc75
jwt:
    access_token_secret: hu8OciRVW-9bGcB4TNsrRijtofosMFKavuFQLoKsM74=
    refresh_token_secret: _3JpO4H1zHA8uCiB8iA5QNBg6S2tNaA2bSGcnus25jI=
    access_token_expiry_time: 2h
    refresh_token_expiry_time: 7d
    issuer: go_blog
mysql:
    host: 127.0.0.1
    port: 3307
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: askanuo1120
    username: root
    password: 051102ydq
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: info
qiniu:
    zone: z2
    bucket: 1askanuo1
    img_path: https://xxx.xxx/
    access_key: XFlYeqpdV29BMb0chpVDOV1kkZtrIRAPLohOa2sg
    secret_key: 7kpI25qXM1B4DhQCTNgiLlAeSy3gOow6mPBN9i7_
    use_https: true
    use_cdn_domains: true
qq:
    enable: false
    app_id: "000000000"
    app_key: xxxxxxxxxxxxxxxx
    redirect_uri: http://xxx.xxx/login?flag=qq
redis:
    address: 127.0.0.1:6379
    password: 051102ydq
    db: 0
system:
    host: 127.0.0.1
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: J-51EzVnP3aH-H8EO5C41OKYmangA45-aSCi4hBro4s=
    oss_type: local
upload:
    size: 20
    path: uploads
website:
    logo: ""
    full_logo: ""
    title: Askanuo's blog
    slogan: Askanuo
    slogan_en: Blog Title
    description: 博客描述
    version: 1.0.0
    created_at: "2025-4-28"
    icp_filing: icp备案号
    public_security_filing: 公安备案号
    github_url: https://github.com/xxx/
    name: 昵称
    job: 工作
    address: 地址
    email: xxx@qq.com
    qq_image: ""
    wechat_image: ""
zap:
    level: info
    filename: log/go_blog.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true